Make login
Salisbury-University/hslinux-web-frontend pull request #9
Opened 2022-09-09 15:13 UTC by ZakHolliman

Creating a pull request to figure out what I need to finish up in order to get the Login page merged into master before moving on to User or Preference Page

2022-09-09 15:59 UTC, SpencerLefever requested changes

2022-09-09 15:59 UTC, SpencerLefever commented on src/http.ts
> +    baseURL: "http://localhost:3005",
Make base url an env variable

2022-09-09 15:59 UTC, SpencerLefever commented on src/stores/auth.ts
> +        .post("/api/v1/auth/login", {
this could also be an env variable

2022-09-09 15:59 UTC, SpencerLefever commented on src/stores/auth.ts
> +          console.log(error);
remove console.log from code before merging to production branch

2022-09-09 16:06 UTC, B-Ryan4 reviewed
Code looks good from what I can tell. I would recommend adding comments to your code so if others need to look at it they can see what is happening

2022-09-18 21:46 UTC, B-Ryan4 commented
looks goos should be ready to go

2022-09-28 16:53 UTC, wrathofrathma approved these changes
Requesting for review is fine, but also don't forget to use the project board to mark what stage it's in. That's what I check for.

Why is there a random empty store file called "response.json"?

2022-09-28 16:53 UTC, wrathofrathma commented on package.json
> +    "dotenv": "^16.0.2",
we ended up not using dotenv on the frontend i think

2022-10-07 15:53 UTC, merged